version: 2

working_directory: &working_directory ~/python-patterns

# Default step config
python3.7: &defaults_python
  docker:
    - image: circleci/python:3.7
      environment:
        TOXENV: ci27,ci37,cov-report
        CODECOV_TOKEN: abafcb30-9d92-4040-a736-6ef71c615cf6
  working_directory: *working_directory

#NPM
restore_package_cache: &restore_package_cache
  restore_cache:
    name: Restore Package Cache
    keys:
      - deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}

save_package_cache: &save_package_cache
  save_cache:
    name: Save Package Cache
    key: deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
    paths:
      - "venv"


workflows:
  version: 2
  build_and_test:
    jobs:
      - build

jobs:
  build:
    <<: *defaults_python

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - *restore_package_cache
      - run:
          command: |
            pip install --upgrade pip
            pip install tox codecov
      - *save_package_cache
      - run:
          name: "code analysis (Test and syntax)"
          command: tox
      - run:
          name: "Codecov"
          command: codecov -e ${TOXENV}
      - run:
          name: "[REPORT] Codecov"
          command: bash <(curl -s https://codecov.io/bash)